[package]
name = "payhelper"
version = "0.1.0"
authors = ["Edgar <git@edgarluque.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
select = "0.5.0"
ureq = "2.0.0"
